services:
  - type: web
    name: data-saver-service
    runtime: docker
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: LOGIN
        sync: false
      - key: PASSWORD
        sync: false
